import { memo, type CSSProperties } from 'react';
import cn from 'classnames';
import {
  CREATURE_FRAME_HEIGHT,
  CREATURE_FRAME_WIDTH,
  getCreatureIdleAssetPath,
  type Creature,
} from '../../data/creatures';

interface PetSpriteProps {
  creature: Creature;
  /** Rendered height in px — width is derived to preserve the 192:208 frame aspect ratio. */
  size?: number;
  className?: string;
}

/**
 * Plays the 8-frame idle loop cropped from a petdex companion pet's
 * spritesheet (see `public/pets/<slug>/idle.webp`, generated by
 * `scripts/generate-pet-sprites.mjs`). Pure CSS steps() animation — no JS
 * timers, no extra re-renders.
 */
function PetSpriteImpl({ creature, size = 64, className }: PetSpriteProps) {
  const scale = size / CREATURE_FRAME_HEIGHT;
  const displayWidth = CREATURE_FRAME_WIDTH * scale;

  // Sprite-sheet steps() trick: the idle strip's grid is 8 columns wide,
  // but not every pet's idle loop actually USES all 8 — shorter loops leave
  // the trailing columns fully transparent (see `Creature.idleFrameCount`,
  // measured per-pet). Only animate through the columns that pet actually
  // has real art in.
  //
  // Within that real range of N frames, the last valid one sits at
  // x = (N-1)*frameWidth. If the keyframe's `to` value were `-N*frameWidth`
  // (one full frame past the last real one) paired with `steps(N)`, the
  // animation's final tick — which browsers do render for a compositor
  // frame right before the loop wraps back to `from` — would land exactly
  // one frame-width beyond the last real frame, i.e. blank/transparent
  // padding. That's the "pet vanishes for an instant" bug.
  //
  // Fix: animate to the LAST valid frame's position, `-(N-1)*frameWidth`,
  // using `steps(N-1)`. Every step lands on a real frame (0..N-1) and the
  // transient final tick re-shows frame N-1 (still a real pose) instead of
  // blank space. Frame N-1 gets a hair less display time than the others —
  // imperceptible for a breathing/blinking idle loop.
  const frameCount = creature.idleFrameCount;
  const cycleDistance = (frameCount - 1) * CREATURE_FRAME_WIDTH;

  const frameStyle = {
    backgroundImage: `url(${getCreatureIdleAssetPath(creature.slug)})`,
    '--pet-sprite-scale': scale,
    '--pet-sprite-cycle-x': `-${cycleDistance}px`,
    '--pet-sprite-steps': frameCount - 1,
  } as CSSProperties;

  return (
    <span
      className={cn('pet-sprite', className)}
      style={{ width: displayWidth, height: size }}
      role="img"
      aria-label={`${creature.displayName}, a TreatPaws genesis pet`}
    >
      <span className="pet-sprite__frame" style={frameStyle} />
    </span>
  );
}

// Memoized so per-second parent re-renders (e.g. useLiveRewards ticking a
// pet card's reward counter) never re-diff or touch this component's DOM
// node — the CSS animation just keeps running undisturbed.
export const PetSprite = memo(PetSpriteImpl);
